### ISSUE TITLE
Make Network More Flexible and Realistic

### ISSUE THREAD

**Issue by naterush** [ethereum/cbc-casper#104]
# Issue
Currently, the network is quite inflexible. It's hard to simulate validators being independent actors, messages arriving in different orders, different message delays, etc.

[Previous PRs](https://github.com/ethereum/cbc-casper/pull/91) to address this were not as flexible as they could be. 

# Proposed Implementation
Implement the network as a message buffer with two functions: 
`send(p, m):` Places (p, m) in the message buffer;
`receive(p):` Deletes some message (p, m) from the buffer and returns m, in which case we say (p, m) is delivered, or returns None and leaves the buffer unchanged.

Note that the buffer may return None on` receive(p)`, even if there is some message for `p` in the buffer. 

Furthermore, the network can take a variety parameters that it can then manage in terms of when it allows messages to propagate, in what order, etc. This should be general enough to allow us to simulate whatever network conditions we want to. 

This is inspired by the FLP impossibility result paper, which can be found [here](https://groups.csail.mit.edu/tds/papers/Lynch/jacm85.pdf).

**Comment by naterush** [comment]
Also worth noting that this probably general enough to allow us to give validators their own "autonomous" actions! We may be able to give them local clocks and liveness strategies and see how the blockchain is built from that.

**Comment by naterush** [comment]
@djrtwo would love to get your input on this :)

**Comment by naterush** [comment]
It's worth noting that there are existing network simulation libraries that exist. From my brief foray into what exists, they all seem too complicated for our purposes.

**Comment by SeanAvery** [comment]
@naterush I am really liking this concept, especially introducing validators as independent actors. 

I have an idea for simulating network connectivity!

## Extending Gaussian Primitives into Random Markov Chain for Validator Randomness ##

Give validators new attributes `self.network_connection`,  `self.sigma`
- let `network_connection` be a scalar between 0 and 99
- if `network_connection` < 50, then receive(p) will return None

The initial value can be set for all validators in gaussian distribution given some global `mu` and `sigma` [much like](https://github.com/ethereum/cbc-casper/blob/master/simulations/utils.py#L76) the initial validator weights.

`n_c = gaussian(n_c, sigma) `

With each round of msg passing, the validators independently calculate a new `network_connection` score based in a gaussian distribution around the previous network connection.

gaussian(n_c, sigma) --> gaussian(n_c', sigma) --> gaussian(n_c'', sigma) --> ...

This will give each validator a smooth & stochastically moving network connection. The `sigma` itself could also vary as such leading to faster/slower variations in connectivity.

**Comment by naterush** [comment]
@SeanAvery yo yo! Thanks for the thoughts, this seems very cool!

The only thing here is that I think it'd be best to keep most of this in the network, rather than pushing it to the validators yet. In a really direct translation of your model, for example, we could maintain all of this in the network, and depending on who calls receive, we give them a message or not. 

The benefit here is that seems much easier to extend to different methods of simulating the network; in some cases, we can just assume a super-synchronous network and make all message propagate perfectly (totally possible with your model as well), but we can also do more complex things like tune the connectivity of specific validators to each other. So it seems like what you propose would be a really interesting "parameter" for the network in general. 

I'll try and get up the (very messy) start of a network rework this weekend - but let me know what you think!

**Comment by naterush** [comment]
TODO: add in partially synchronous blockchain assumption (increasing timeouts).

**Comment by naterush** [comment]
Target DAG. And then we try and target that.

**Comment by naterush** [comment]
Can be closed after this PR: https://github.com/ethereum/cbc-casper/pull/151

Moving DAG targeting to an issue about validator strategies.
