### ISSUE TITLE
Formalize "Release" Process

### ISSUE THREAD

**Issue by naterush** [ethereum/cbc-casper#112]
# Issue
Currently, we merge all PRs into `master.` This means some onlooker/potential contributor might stumble upon the code base while it's in the middle of a transition process. 

# Proposed Implementation
- [x] Create a `develop` branch to which all PRs should be merged into
- [x] Decide on a release schedule for merging `develop` into `master`
- [ ] Add "Dev/Release Process" to wiki

Possible options include:
1. Merging into master at major, stable milestones (e.g. network refactor, testing language refactor, etc)
2. Consistent releases with some time interval, where all features that are stable by this time are merged into master.

**Comment by naterush** [comment]
I'm for option 1, personally, but thought we should discuss what others thought was best. @djrtwo would love to hear your thoughts :)

**Comment by djrtwo** [comment]
Yeah, with our potentially erratic dev cycles, we should just merge into master and cut a version when we're ready with some new stuffs.

**Comment by djrtwo** [comment]
Do we need to put this anywhere? Probably best lives in the wiki that doesn't exist.

**Comment by zramsay** [comment]
we can have circle push out a release on merges to master

**Comment by naterush** [comment]
Closing. Release process is probably as formal as it deserves to be currently :)
