### ISSUE TITLE
Add in EVM consensus

### ISSUE THREAD

**Issue by naterush** [ethereum/cbc-casper#127]
# Issue
EVM blocks/transactions should be able to be consensussed upon using the CBC Casper framework.

# Proposed Implementation
- Integrate pyEVM into a `Protocol`
- Message becomes an EVM block/txs
- Estimate is GHOST like our current `Block` estimate

**Comment by naterush** [comment]
Message becomes EVM block/txs

**Comment by vladzamfir** [comment]
Suggest splitting this into two issues

**Comment by djrtwo** [comment]
on it

**Comment by naterush** [comment]
I'm going to close this for now. As discussed with Vlad, adding the EVM actually doesn't give us much useful simulation information with CBC protocol (as we essentially are just adding TXs into blocks).
