### ISSUE TITLE
Validator strategy

### ISSUE THREAD

**Issue by naterush** [ethereum/cbc-casper#131]
# Issue
- What's wrong?
- How are things currently?
- How should things be?

# Proposed Implementation
Target DAG (start with targeting a round robin)

**Comment by naterush** [comment]
Maybe also every node having a poisson process and generating blocks...

**Comment by djrtwo** [comment]
`def make_new_message(view, time)` return bool

**Comment by naterush** [comment]
Duplicated in different issue. Closing.
