### ISSUE TITLE
Implement a synchrony layer (?)

### ISSUE THREAD

**Issue by vladzamfir** [ethereum/cbc-casper#133]
# Issue
- What's wrong?
- How are things currently?
- How should things be?

# Proposed Implementation
Add for example rules like
"If for 2 weeks this has been my estimate, then decide on it"
"If you spam me, you're Byzantine"
"If you're censoring, you're Byzantine"

**Comment by naterush** [comment]
Going to close this issue for now. I think it's out-of-scope of the simulations (at least for now).
