### ISSUE TITLE
OrderView should inherit from some standard view

### ISSUE THREAD

**Issue by djrtwo** [ethereum/cbc-casper#142]
# Issue
OrderView is pretty much the same as BinaryView and IntegerView.
These guys should all inherit from some common view like ValueView.

# Proposed Implementation
- Ensure OrderView is not repeating a bunch of code
- Maybe move guts of IntegerView to something like ValueView
- should use initial_message from OrderProtocol

**Comment by naterush** [comment]
Hmm. The gains here are relatively minor (and the codebase might actually suffer in terms of readability. 

Closing for now.
