### ISSUE TITLE
Add descriptive comments to casper.py

### ISSUE THREAD

**Issue by naterush** [ethereum/cbc-casper#147]
# Issue
Add a default message generation scheme.

# Proposed Implementation
Just add to configs and to parser.

**Comment by djrtwo** [comment]
Does the parser need comments? I find the "help" message in each to be very descriptive and a comment would likely just repeat the info.

I agree the default_config could use a comment on what it is and how to adjust.

**Comment by naterush** [comment]
Yep, with ya here. I think they are enough. Closing!
