### ISSUE TITLE
Network.send to handle sender other than message.sender

### ISSUE THREAD

**Issue by djrtwo** [ethereum/cbc-casper#153]
# Issue
`Network.send` currently assumes the sender is the `message.sender` when calculating the `delay` for receipt by the receiver. This is okay for now, but would be limiting if we modeled a Network with peers and a gossip protocol.

# Proposed Implementation
- Change `Network.send` function signature to `(sender, receiver, message)` and use the delay of `delay(sender, receiver)`

**Comment by naterush** [comment]
Closing, as networks no longer in use. This functionality is currently supported by the network delay functions.
