### ISSUE TITLE
Add ability to specify initial bets

### ISSUE THREAD

**Issue by naterush** [ethereum/cbc-casper#161]
# Issue
Currently, for some protocols, each validator is randomly assigned an initial starting estimate. For example, in Binary consensus, each validator is [randomly assigned](https://github.com/ethereum/cbc-casper/blob/master/casper/protocols/binary/binary_protocol.py#L19) an initial estimate. Ideally, we would be able to control these initial estimates.

# Proposed Implementation
Protocols can store a dictionary from validator name => initial estimate, in the protocols that it makes sense. Some function can populate this dictionary with initial estimates.

If some initial messages are specific, the validators should use these in their first bet. Otherwise, they can choose a random estimate, as they do currently.

**Comment by djrtwo** [comment]
Seems reasonable.

**Comment by naterush** [comment]
Addressed https://github.com/ethereum/cbc-casper/issues/175
