### ISSUE TITLE
add special validator number to check the global forkchoice

### ISSUE THREAD

**Issue by zramsay** [ethereum/cbc-casper#42]
https://github.com/karlfloersch/cbc-casper/blob/071655de04e9ee1bc4393a7d853a683de4b6f44d/casper/testing_language.py#L126

**Comment by AFDudley** [comment]
Does anyone besides Karl understand what this means?

**Comment by djrtwo** [comment]
Pretty sure this can be closed. We track global view in the simulations and
can run forkchoice on it without a "special validator"

**Comment by djrtwo** [comment]
It was written by @naterush so I'll wait for him to chime in before I close.

**Comment by naterush** [comment]
This is a reference to the testing language. I wanted a way of checking the global forkchoice w/ an assertion like `CH999-A`, where `A` is the global forkchoice, and `999` is the number that we use to represent the global forkchoice. Will add this to the testing language PR open currently, and then close this.

**Comment by naterush** [comment]
Closing.
