### ISSUE TITLE
Run tests against multiple oracles.

### ISSUE THREAD

**Issue by djrtwo** [ethereum/cbc-casper#53]
# Issue
Tests are only run with CliqueOracle in TestLang and Validator. All relevant tests should run against CliqueOracle and AdversaryOracle.

# Proposed Implementation
- [x] Make oracle used by Validator and TestLang configurable
- [ ] Run tests requiring oracles against a list of Oracles.

Note: TestLang only uses the oracle for --report option.

**Comment by naterush** [comment]
This is addressed in https://github.com/ethereum/cbc-casper/pull/164
