### ISSUE TITLE
bets included in justification, instead of hash-linking

### ISSUE THREAD

**Issue by vladzamfir** [ethereum/cbc-casper#6]
I think fixing this will involve some healthy refactoring in validator.py.

the validator will need to keep bets for that they don't have dependencies (that satisfy the hash link/commitment) in "limbo". It separates receive_bet from 'add_bet_to_view' (name bad, tentative) which makes it possible to use a bet in safety calculation.

It also would mean that the size of bets on the network won't the size of its entire dependency - this will play into our network.py/casper.py refactoring

**Comment by naterush** [comment]
Addressed in PR here: https://github.com/ethereum/cbc-casper/pull/106
