### ISSUE TITLE
Assess finality gadget use of ethereum network data in simulations

### ISSUE THREAD

**Issue by djrtwo** [ethereum/cbc-casper#61]
# Issue
Supposedly somewhere in pyethereum/finality gadget repo are some network simulations that use real ethereum network data. We are discussing adding some complexity to the simulations and want to see if this stuff in the ethereum repo could be of use.

# Proposed Implementation
- Reach out to @karlfloersch to see where this stuff is
- Discuss relevance here.

**Comment by naterush** [comment]
Networking was refactored in PR: https://github.com/ethereum/cbc-casper/pull/151

Unless we decide to make this simulation very realistic, this is probably enough for our purposes. Closing.
