### ISSUE TITLE
Add test_string output for experiments

### ISSUE THREAD

**Issue by djrtwo** [ethereum/cbc-casper#85]
# Issue
There is no way to re-run experimental results or to analyze/visualize what actually happened each run.

# Proposed Implementation
- For each simulation run in the experiment, output a corresponding weights dictionary and test_string so it can be re-run/visualized with test_lang
- use and output a seed for rand so the exact experiment can be re-run
- seed rand with "seed" if provided in an experiment.

**Comment by naterush** [comment]
@djrtwo what's the feasibility to adding this to the network currently? Seems like we can just remember what messages were delivered when from each queue, and there shouldn't be any ordering issues unless I'm missing something.

**Comment by naterush** [comment]
Addressed in redesign! We output the entire execution as a JSON string :)
