### ISSUE TITLE
Remove default to blockchain

### ISSUE THREAD

**Issue by djrtwo** [ethereum/cbc-casper#87]
# Issue
System currently defaults to "blockchain" protocol where ever possible. This shouldn't be the case.

# Proposed Implementation
- [x] move protocol specific tests into `tests/casper/*protocol_name*`
- [x] refactor testing to be generic where possible, and to test specific protocols where doing so
- [x] Maybe provide minimum implementations of most methods on the abstract classes (message and view) so that generic tests can pass
- [x] make testlang protocol agnostic
- [x] pass in protocol as a param to casper.py
- [x] require specify protocol in experiment .json file
- [ ] Will have to make a specific analyzer to each protocol. i.e. BlockchainAnalyzer

**Comment by naterush** [comment]
Most of this has been addressed. Cool! Closing :)
