### ISSUE TITLE
update make commands

### ISSUE THREAD

**Issue by naterush** [ethereum/cbc-casper#95]
# Issue
Default commands don't give as much flexibility as they should (we want nice commands to run all types of protocols in all types of situations!)

# Proposed Implementation
Extend commands in make file to be more diverse and cover more interesting situations.

**Comment by naterush** [comment]
As a side note to this, it would be cool to show off the network in the case of interesting situations. For example, we could have a command called make run-network-split, which shows how casper handles an extended network split. 

This could be very cool for people trying to visualize the situations.

**Comment by djrtwo** [comment]
great idea!!

**Comment by zramsay** [comment]
sort of duplicate of #70?

I would lean toward having most settings in the `config.ini`, rather than flags. A nice config with all the defaults is self-documented

**Comment by naterush** [comment]
Addressed in protocol redesign.
