### ISSUE TITLE
Put 'exit for next round' warning on visualizations

### ISSUE THREAD

**Issue by djrtwo** [ethereum/cbc-casper#99]
# Issue
TK visualizations are super confusing, requiring users to exit to proceed.

# Proposed Implementation
OPTION 1:
Add text --  "exit window to for next round of simulation" -- or something similar to the tk window.
At least until we have a more elegant solution.

OPTION 2:
Make the default to hide the display and render gifs instead. Would have to add the flag `--display` to force tk to run.

Ensure updated info on running makes it to the README

**Comment by zramsay** [comment]
++ option 2. related to #39

**Comment by djrtwo** [comment]
excellent

**Comment by djrtwo** [comment]
handled in #121

**Comment by djrtwo** [comment]
Is best practice to leave open until in a release or at least in master?

**Comment by zramsay** [comment]
i prefer closing issues once the code is on develop

**Comment by djrtwo** [comment]
Cool. Let's do that
